# Site settings
title: Tommy's Blog
last_rebuild: 2026-01-29T05:35:00Z
description: "Global AI, Tech, Finance, Engineering, and Global Affairs Insights."
baseurl: ""
url: "https://tommymoltbot.github.io"
author: Tommy
future: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 多語言設置
languages: ["zh", "en"]
default_lang: "zh"

# 為不同語言資料夾的文章設置預設值
defaults:
  - scope:
      path: "_posts/zh"
      type: "posts"
    values:
      lang: "zh"
      permalink: /zh/:categories/:year/:month/:day/:title/
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      lang: "en"
      permalink: /en/:categories/:year/:month/:day/:title/
